steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args: ["-c", "gcloud app deploy --quiet"]

options:
  logging: CLOUD_LOGGING_ONLY

# Specify a region that is not restricted
region: europe-west6
